### PR TITLE
Fix circular dependency

### PR DESCRIPTION
**Pull request by BogdanDarius**
In the latest version of smelte 0.2.1 I observed a circular dependency warning:
` (!) Circular dependency: node_modules/smelte/src/index.js -> node_modules/smelte/src/components/NavigationDrawer/index.js -> node_modules/smelte/src/co
mponents/NavigationDrawer/NavigationDrawer.svelte -> node_modules/smelte/src/index.js`

### CODE REVIEW

**Comment by matyunya** [comment]
We still want to expose breakpoints in imports.

**Comment by BogdanDarius** [comment]
Maybe putting them in utils?

**Comment by matyunya** [comment]
wouldn't it fix the circular dependency error just by changing the import statement?

**Comment by BogdanDarius** [comment]
Of course it will work, but everytime we are gonna import breakpoints in the components we are going to get a circular dependency.

**Comment by matyunya** [comment]
Alright, looks good, we're exporting breakpoints already anyway

**Comment by matyunya** [comment]
Oh, but can you please fix the conflict?

**Pull request closed without merging**
